export { default as Home } from './home'
export { default as NotFound } from './not-found'
export { default as Plans } from './plans'
export { default as Relative } from './relative'
export { default as Thanks } from './thanks'
